name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore

      - name: Publish Release
        run: >
          dotnet publish winforms/DRSaveTracker.csproj \
            -c Release \
            -r win-x64 \
            -o publish \
            --self-contained true \
            -p:PublishSingleFile=true \
            -p:DebugType=None \
            -p:DebugSymbols=false \
            -p:PublishSingleFile=true \
            -p:PublishTrimmed=false
            
      - name: Remove PDB files
        shell: pwsh
        run: |
          Get-ChildItem publish -Filter *.pdb -Recurse | Remove-Item -Force

      - name: Zip publish folder
        shell: pwsh
        run: |
          Compress-Archive -Path publish\* -DestinationPath MyApp-win-x64.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DRSaveTracker-win-x64
          path: DRSaveTracker-win-x64.zip
